### ISSUE TITLE
Path issue on some environments

### ISSUE THREAD

**Issue by jenstornell** [jenstornell/kirby-seo#23]
vardagsfinans.se

**Comment by abroess** [comment]
I've got the same issue on a localhost installation. Perhaps a little workaround will help:

```
// Url preview
public static function urlPreview( $url ) {
    $url_parts = parse_url($url);
    $scheme = ( $url_parts['scheme'] == 'https' ) ? 'https://' : '';
    if( empty($url_parts['path'] ) ) {
        $uri = $scheme . $url_parts['host'];
    } else {
        $uri = $scheme . $url_parts['host'] . $url_parts['path'];
    }

    return $uri;
}
```

**Comment by bezin** [comment]
I can confirm this. @abroess fix helped me as well

**Comment by TimOetting** [comment]
I can confirm this too

**Comment by luxlogica** [comment]
This seems to be the same error as reported in Issue #30.

Can still confirm the same issue with Kirby 2.5.4, running on a Mac with MAMP.

Can also confirm that the fix proposed by @abroess fixed it! 👍 

Perhaps this should be added to the next version, and this bug closed?

**Comment by abroess** [comment]
I made a pull request #43

**Comment by jenstornell** [comment]
Sorry for the delay. I will make a complete rewrite of this field for Kirby 3. But now that @abroess sent me a pull request I've merged it. I simply trust in your comments that it's working.

Thanks!
