### ISSUE TITLE
Error in path

### ISSUE THREAD

**Issue by jenstornell** [jenstornell/kirby-seo#30]
https://forum.getkirby.com/t/kirby-seo-serp-preview-field-for-the-panel/3605/49

>On one Server Configuration I've got an issue with this plugin
>Giving error Message just on the home Page saying:
>Undefined index: path

**Comment by luxlogica** [comment]
This seems to be a repeat of Issue #23 - and there seems to be a working fix for this described there.

**Comment by luxlogica** [comment]
@jenstornell I believe this issue can be closed now - fixed long with issue #23, by pull request #43 👍

**Comment by jenstornell** [comment]
@luxlogica It seems like it. Closing it.
